//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatSpeak.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatPhrases
    {
        public int Id { get; set; }
        public string CatDialect { get; set; }
        public string MeowSound { get; set; }
        public string HumanTranslation { get; set; }
        public Nullable<int> DangerLevel { get; set; }
    }
}
