//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatSpeak.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> TranslatorId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Status { get; set; }
        public string FinalTranslation { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Cats Cats { get; set; }
        public virtual Users Users { get; set; }
        public virtual Translators Translators { get; set; }
    }
}
